
#ifndef _H_y_microwave_model
#define _H_y_microwave_model
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.5-5

    Yuma SIL header
    module microwave-model
    revision 2017-03-24
    namespace urn:onf:params:xml:ns:yang:microwave-model
    organization ONF (Open Networking Foundation) Open Transport Working Group - Wireless Transport Project

 */

#include <xmlstring.h>

#include "dlq.h"
#include "ncxtypes.h"
#include "op.h"
#include "status.h"
#include "val.h"

#ifdef __cplusplus
extern "C" {
#endif

#define y_microwave_model_M_microwave_model (const xmlChar *)"microwave-model"
#define y_microwave_model_R_microwave_model (const xmlChar *)"2017-03-24"

#define y_microwave_model_N_adaptive_modulation_is_avail (const xmlChar *)"adaptive-modulation-is-avail"
#define y_microwave_model_N_adaptive_modulation_is_on (const xmlChar *)"adaptive-modulation-is-on"
#define y_microwave_model_N_administrative_state (const xmlChar *)"administrative-state"
#define y_microwave_model_N_air_interface_capability (const xmlChar *)"air-interface-capability"
#define y_microwave_model_N_air_interface_configuration (const xmlChar *)"air-interface-configuration"
#define y_microwave_model_N_air_interface_current_performance (const xmlChar *)"air-interface-current-performance"
#define y_microwave_model_N_air_interface_current_problems (const xmlChar *)"air-interface-current-problems"
#define y_microwave_model_N_air_interface_diversity (const xmlChar *)"air-interface-diversity"
#define y_microwave_model_N_air_interface_diversity_capability (const xmlChar *)"air-interface-diversity-capability"
#define y_microwave_model_N_air_interface_diversity_configuration (const xmlChar *)"air-interface-diversity-configuration"
#define y_microwave_model_N_air_interface_diversity_current_performance (const xmlChar *)"air-interface-diversity-current-performance"
#define y_microwave_model_N_air_interface_diversity_current_problems (const xmlChar *)"air-interface-diversity-current-problems"
#define y_microwave_model_N_air_interface_diversity_historical_performances (const xmlChar *)"air-interface-diversity-historical-performances"
#define y_microwave_model_N_air_interface_diversity_status (const xmlChar *)"air-interface-diversity-status"
#define y_microwave_model_N_air_interface_historical_performances (const xmlChar *)"air-interface-historical-performances"
#define y_microwave_model_N_air_interface_hsb_configuration_is_faulty_severity (const xmlChar *)"air-interface-hsb-configuration-is-faulty-severity"
#define y_microwave_model_N_air_interface_hsb_is_down_severity (const xmlChar *)"air-interface-hsb-is-down-severity"
#define y_microwave_model_N_air_interface_hsb_is_partly_down_severity (const xmlChar *)"air-interface-hsb-is-partly-down-severity"
#define y_microwave_model_N_air_interface_list (const xmlChar *)"air-interface-list"
#define y_microwave_model_N_air_interface_ltp_list (const xmlChar *)"air-interface-ltp-list"
#define y_microwave_model_N_air_interface_name (const xmlChar *)"air-interface-name"
#define y_microwave_model_N_air_interface_status (const xmlChar *)"air-interface-status"
#define y_microwave_model_N_alic_is_avail (const xmlChar *)"alic-is-avail"
#define y_microwave_model_N_alic_is_on (const xmlChar *)"alic-is-on"
#define y_microwave_model_N_alic_is_up (const xmlChar *)"alic-is-up"
#define y_microwave_model_N_am_downshift_level (const xmlChar *)"am-downshift-level"
#define y_microwave_model_N_am_upshift_level (const xmlChar *)"am-upshift-level"
#define y_microwave_model_N_atpc_is_avail (const xmlChar *)"atpc-is-avail"
#define y_microwave_model_N_atpc_is_on (const xmlChar *)"atpc-is-on"
#define y_microwave_model_N_atpc_is_up (const xmlChar *)"atpc-is-up"
#define y_microwave_model_N_atpc_range (const xmlChar *)"atpc-range"
#define y_microwave_model_N_atpc_thresh_lower (const xmlChar *)"atpc-thresh-lower"
#define y_microwave_model_N_atpc_thresh_upper (const xmlChar *)"atpc-thresh-upper"
#define y_microwave_model_N_attribute_name (const xmlChar *)"attribute-name"
#define y_microwave_model_N_attribute_value_changed_notification (const xmlChar *)"attribute-value-changed-notification"
#define y_microwave_model_N_auto_freq_select_is_avail (const xmlChar *)"auto-freq-select-is-avail"
#define y_microwave_model_N_auto_freq_select_is_on (const xmlChar *)"auto-freq-select-is-on"
#define y_microwave_model_N_auto_freq_select_is_up (const xmlChar *)"auto-freq-select-is-up"
#define y_microwave_model_N_auto_freq_select_range (const xmlChar *)"auto-freq-select-range"
#define y_microwave_model_N_available_kinds_of_diversity (const xmlChar *)"available-kinds-of-diversity"
#define y_microwave_model_N_bundling_is_avail (const xmlChar *)"bundling-is-avail"
#define y_microwave_model_N_channel_bandwidth (const xmlChar *)"channel-bandwidth"
#define y_microwave_model_N_co_channel_group (const xmlChar *)"co-channel-group"
#define y_microwave_model_N_co_channel_group_id (const xmlChar *)"co-channel-group-id"
#define y_microwave_model_N_code_rate (const xmlChar *)"code-rate"
#define y_microwave_model_N_code_rate_cur (const xmlChar *)"code-rate-cur"
#define y_microwave_model_N_container_id (const xmlChar *)"container-id"
#define y_microwave_model_N_container_type (const xmlChar *)"container-type"
#define y_microwave_model_N_counter (const xmlChar *)"counter"
#define y_microwave_model_N_cryptographic_key (const xmlChar *)"cryptographic-key"
#define y_microwave_model_N_cses (const xmlChar *)"cses"
#define y_microwave_model_N_current_performance_data_list (const xmlChar *)"current-performance-data-list"
#define y_microwave_model_N_current_problem_list (const xmlChar *)"current-problem-list"
#define y_microwave_model_N_defect_blocks_sum (const xmlChar *)"defect-blocks-sum"
#define y_microwave_model_N_diversity_name (const xmlChar *)"diversity-name"
#define y_microwave_model_N_duplex_distance (const xmlChar *)"duplex-distance"
#define y_microwave_model_N_duplex_distance_is_variable (const xmlChar *)"duplex-distance-is-variable"
#define y_microwave_model_N_elapsed_time (const xmlChar *)"elapsed-time"
#define y_microwave_model_N_encryption_is_avail (const xmlChar *)"encryption-is-avail"
#define y_microwave_model_N_encryption_is_on (const xmlChar *)"encryption-is-on"
#define y_microwave_model_N_endpoint (const xmlChar *)"endpoint"
#define y_microwave_model_N_es (const xmlChar *)"es"
#define y_microwave_model_N_ethernet_container_capability (const xmlChar *)"ethernet-container-capability"
#define y_microwave_model_N_ethernet_container_configuration (const xmlChar *)"ethernet-container-configuration"
#define y_microwave_model_N_ethernet_container_current_performance (const xmlChar *)"ethernet-container-current-performance"
#define y_microwave_model_N_ethernet_container_current_problems (const xmlChar *)"ethernet-container-current-problems"
#define y_microwave_model_N_ethernet_container_historical_performances (const xmlChar *)"ethernet-container-historical-performances"
#define y_microwave_model_N_ethernet_container_status (const xmlChar *)"ethernet-container-status"
#define y_microwave_model_N_fcswitch (const xmlChar *)"fcswitch"
#define y_microwave_model_N_granularity_period (const xmlChar *)"granularity-period"
#define y_microwave_model_N_historical_performance_data_list (const xmlChar *)"historical-performance-data-list"
#define y_microwave_model_N_history_data_id (const xmlChar *)"history-data-id"
#define y_microwave_model_N_hybrid_mw_structure_capability (const xmlChar *)"hybrid-mw-structure-capability"
#define y_microwave_model_N_hybrid_mw_structure_configuration (const xmlChar *)"hybrid-mw-structure-configuration"
#define y_microwave_model_N_hybrid_mw_structure_current_performance (const xmlChar *)"hybrid-mw-structure-current-performance"
#define y_microwave_model_N_hybrid_mw_structure_current_problems (const xmlChar *)"hybrid-mw-structure-current-problems"
#define y_microwave_model_N_hybrid_mw_structure_historical_performances (const xmlChar *)"hybrid-mw-structure-historical-performances"
#define y_microwave_model_N_hybrid_mw_structure_status (const xmlChar *)"hybrid-mw-structure-status"
#define y_microwave_model_N_ipv4_compression_is_avail (const xmlChar *)"ipv4-compression-is-avail"
#define y_microwave_model_N_ipv4_compression_is_on (const xmlChar *)"ipv4-compression-is-on"
#define y_microwave_model_N_ipv6_compression_is_avail (const xmlChar *)"ipv6-compression-is-avail"
#define y_microwave_model_N_ipv6_compression_is_on (const xmlChar *)"ipv6-compression-is-on"
#define y_microwave_model_N_last_status_change (const xmlChar *)"last-status-change"
#define y_microwave_model_N_layer2_compression_is_avail (const xmlChar *)"layer2-compression-is-avail"
#define y_microwave_model_N_layer2_compression_is_on (const xmlChar *)"layer2-compression-is-on"
#define y_microwave_model_N_layer4_compression_is_avail (const xmlChar *)"layer4-compression-is-avail"
#define y_microwave_model_N_layer4_compression_is_on (const xmlChar *)"layer4-compression-is-on"
#define y_microwave_model_N_layer_protocol (const xmlChar *)"layer-protocol"
#define y_microwave_model_N_link_is_up (const xmlChar *)"link-is-up"
#define y_microwave_model_N_local_end_point_id (const xmlChar *)"local-end-point-id"
#define y_microwave_model_N_logical_termination_point (const xmlChar *)"logical-termination-point"
#define y_microwave_model_N_loop_back_kind_on (const xmlChar *)"loop-back-kind-on"
#define y_microwave_model_N_loop_back_kind_up (const xmlChar *)"loop-back-kind-up"
#define y_microwave_model_N_maintenance_timer (const xmlChar *)"maintenance-timer"
#define y_microwave_model_N_maintenance_timer_range (const xmlChar *)"maintenance-timer-range"
#define y_microwave_model_N_max_number_of_segments_reservable (const xmlChar *)"max-number-of-segments-reservable"
#define y_microwave_model_N_mimo_channels (const xmlChar *)"mimo-channels"
#define y_microwave_model_N_mimo_is_avail (const xmlChar *)"mimo-is-avail"
#define y_microwave_model_N_mimo_is_on (const xmlChar *)"mimo-is-on"
#define y_microwave_model_N_mimo_is_up (const xmlChar *)"mimo-is-up"
#define y_microwave_model_N_modulation_cur (const xmlChar *)"modulation-cur"
#define y_microwave_model_N_modulation_is_on (const xmlChar *)"modulation-is-on"
#define y_microwave_model_N_modulation_max (const xmlChar *)"modulation-max"
#define y_microwave_model_N_modulation_min (const xmlChar *)"modulation-min"
#define y_microwave_model_N_modulation_scheme (const xmlChar *)"modulation-scheme"
#define y_microwave_model_N_mpls_compression_is_avail (const xmlChar *)"mpls-compression-is-avail"
#define y_microwave_model_N_mpls_compression_is_on (const xmlChar *)"mpls-compression-is-on"
#define y_microwave_model_N_mw_air_interface_diversity_pac (const xmlChar *)"mw-air-interface-diversity-pac"
#define y_microwave_model_N_mw_air_interface_hsb_end_point_pac (const xmlChar *)"mw-air-interface-hsb-end-point-pac"
#define y_microwave_model_N_mw_air_interface_hsb_fc_switch_pac (const xmlChar *)"mw-air-interface-hsb-fc-switch-pac"
#define y_microwave_model_N_mw_air_interface_pac (const xmlChar *)"mw-air-interface-pac"
#define y_microwave_model_N_mw_ethernet_container_pac (const xmlChar *)"mw-ethernet-container-pac"
#define y_microwave_model_N_mw_hybrid_mw_structure_pac (const xmlChar *)"mw-hybrid-mw-structure-pac"
#define y_microwave_model_N_mw_pure_ethernet_structure_pac (const xmlChar *)"mw-pure-ethernet-structure-pac"
#define y_microwave_model_N_mw_tdm_container_pac (const xmlChar *)"mw-tdm-container-pac"
#define y_microwave_model_N_name_binding (const xmlChar *)"name-binding"
#define y_microwave_model_N_new_value (const xmlChar *)"new-value"
#define y_microwave_model_N_number_of_air_interfaces_max (const xmlChar *)"number-of-air-interfaces-max"
#define y_microwave_model_N_number_of_tdm_segments_to_be_reserved (const xmlChar *)"number-of-tdm-segments-to-be-reserved"
#define y_microwave_model_N_object_class (const xmlChar *)"object-class"
#define y_microwave_model_N_object_creation_notification (const xmlChar *)"object-creation-notification"
#define y_microwave_model_N_object_deletion_notification (const xmlChar *)"object-deletion-notification"
#define y_microwave_model_N_object_id_ref (const xmlChar *)"object-id-ref"
#define y_microwave_model_N_object_type (const xmlChar *)"object-type"
#define y_microwave_model_N_obsolete_drop_order_rank (const xmlChar *)"obsolete-drop-order-rank"
#define y_microwave_model_N_obsolete_priority_class (const xmlChar *)"obsolete-priority-class"
#define y_microwave_model_N_operational_status (const xmlChar *)"operational-status"
#define y_microwave_model_N_packet_compression_is_avail (const xmlChar *)"packet-compression-is-avail"
#define y_microwave_model_N_packet_compression_is_on (const xmlChar *)"packet-compression-is-on"
#define y_microwave_model_N_performance_data (const xmlChar *)"performance-data"
#define y_microwave_model_N_period_end_time (const xmlChar *)"period-end-time"
#define y_microwave_model_N_polarization (const xmlChar *)"polarization"
#define y_microwave_model_N_power_is_on (const xmlChar *)"power-is-on"
#define y_microwave_model_N_problem (const xmlChar *)"problem"
#define y_microwave_model_N_problem_kind_name (const xmlChar *)"problem-kind-name"
#define y_microwave_model_N_problem_kind_severity (const xmlChar *)"problem-kind-severity"
#define y_microwave_model_N_problem_kind_severity_list (const xmlChar *)"problem-kind-severity-list"
#define y_microwave_model_N_problem_name (const xmlChar *)"problem-name"
#define y_microwave_model_N_problem_notification (const xmlChar *)"problem-notification"
#define y_microwave_model_N_problem_severity (const xmlChar *)"problem-severity"
#define y_microwave_model_N_prot_type (const xmlChar *)"prot-type"
#define y_microwave_model_N_pure_ethernet_structure_capability (const xmlChar *)"pure-ethernet-structure-capability"
#define y_microwave_model_N_pure_ethernet_structure_configuration (const xmlChar *)"pure-ethernet-structure-configuration"
#define y_microwave_model_N_pure_ethernet_structure_current_performance (const xmlChar *)"pure-ethernet-structure-current-performance"
#define y_microwave_model_N_pure_ethernet_structure_current_problems (const xmlChar *)"pure-ethernet-structure-current-problems"
#define y_microwave_model_N_pure_ethernet_structure_historical_performances (const xmlChar *)"pure-ethernet-structure-historical-performances"
#define y_microwave_model_N_pure_ethernet_structure_status (const xmlChar *)"pure-ethernet-structure-status"
#define y_microwave_model_N_q_in_q_compression_is_avail (const xmlChar *)"q-in-q-compression-is-avail"
#define y_microwave_model_N_q_in_q_compression_is_on (const xmlChar *)"q-in-q-compression-is-on"
#define y_microwave_model_N_radio_power_is_up (const xmlChar *)"radio-power-is-up"
#define y_microwave_model_N_radio_signal_id (const xmlChar *)"radio-signal-id"
#define y_microwave_model_N_receiver_is_on (const xmlChar *)"receiver-is-on"
#define y_microwave_model_N_remote_end_point_id (const xmlChar *)"remote-end-point-id"
#define y_microwave_model_N_rf_temp_avg (const xmlChar *)"rf-temp-avg"
#define y_microwave_model_N_rf_temp_cur (const xmlChar *)"rf-temp-cur"
#define y_microwave_model_N_rf_temp_max (const xmlChar *)"rf-temp-max"
#define y_microwave_model_N_rf_temp_min (const xmlChar *)"rf-temp-min"
#define y_microwave_model_N_role (const xmlChar *)"role"
#define y_microwave_model_N_rx_channel_bandwidth (const xmlChar *)"rx-channel-bandwidth"
#define y_microwave_model_N_rx_frequency (const xmlChar *)"rx-frequency"
#define y_microwave_model_N_rx_frequency_cur (const xmlChar *)"rx-frequency-cur"
#define y_microwave_model_N_rx_frequency_max (const xmlChar *)"rx-frequency-max"
#define y_microwave_model_N_rx_frequency_min (const xmlChar *)"rx-frequency-min"
#define y_microwave_model_N_rx_level_avg (const xmlChar *)"rx-level-avg"
#define y_microwave_model_N_rx_level_cur (const xmlChar *)"rx-level-cur"
#define y_microwave_model_N_rx_level_max (const xmlChar *)"rx-level-max"
#define y_microwave_model_N_rx_level_min (const xmlChar *)"rx-level-min"
#define y_microwave_model_N_rx_threshold (const xmlChar *)"rx-threshold"
#define y_microwave_model_N_scanner_id (const xmlChar *)"scanner-id"
#define y_microwave_model_N_segment_id (const xmlChar *)"segment-id"
#define y_microwave_model_N_segment_id_ref (const xmlChar *)"segment-id-ref"
#define y_microwave_model_N_segment_is_reserved_for_tdm (const xmlChar *)"segment-is-reserved-for-tdm"
#define y_microwave_model_N_segment_status_list (const xmlChar *)"segment-status-list"
#define y_microwave_model_N_segment_status_type_id (const xmlChar *)"segment-status-type-id"
#define y_microwave_model_N_segments_id_list (const xmlChar *)"segments-id-list"
#define y_microwave_model_N_sequence_number (const xmlChar *)"sequence-number"
#define y_microwave_model_N_ses (const xmlChar *)"ses"
#define y_microwave_model_N_severity (const xmlChar *)"severity"
#define y_microwave_model_N_snir_avg (const xmlChar *)"snir-avg"
#define y_microwave_model_N_snir_cur (const xmlChar *)"snir-cur"
#define y_microwave_model_N_snir_max (const xmlChar *)"snir-max"
#define y_microwave_model_N_snir_min (const xmlChar *)"snir-min"
#define y_microwave_model_N_sort_of_co_channel_group (const xmlChar *)"sort-of-co-channel-group"
#define y_microwave_model_N_structure_id (const xmlChar *)"structure-id"
#define y_microwave_model_N_structure_id_ref (const xmlChar *)"structure-id-ref"
#define y_microwave_model_N_structure_type (const xmlChar *)"structure-type"
#define y_microwave_model_N_supported_alarms (const xmlChar *)"supported-alarms"
#define y_microwave_model_N_supported_channel_plan (const xmlChar *)"supported-channel-plan"
#define y_microwave_model_N_supported_channel_plan_list (const xmlChar *)"supported-channel-plan-list"
#define y_microwave_model_N_supported_loop_back_kind_list (const xmlChar *)"supported-loop-back-kind-list"
#define y_microwave_model_N_supported_tdm_container_types_list (const xmlChar *)"supported-tdm-container-types-list"
#define y_microwave_model_N_supported_tdm_structure_types_list (const xmlChar *)"supported-tdm-structure-types-list"
#define y_microwave_model_N_suspect_interval_flag (const xmlChar *)"suspect-interval-flag"
#define y_microwave_model_N_tdm_container_capability (const xmlChar *)"tdm-container-capability"
#define y_microwave_model_N_tdm_container_configuration (const xmlChar *)"tdm-container-configuration"
#define y_microwave_model_N_tdm_container_current_performance (const xmlChar *)"tdm-container-current-performance"
#define y_microwave_model_N_tdm_container_current_problems (const xmlChar *)"tdm-container-current-problems"
#define y_microwave_model_N_tdm_container_historical_performances (const xmlChar *)"tdm-container-historical-performances"
#define y_microwave_model_N_tdm_container_name (const xmlChar *)"tdm-container-name"
#define y_microwave_model_N_tdm_container_size (const xmlChar *)"tdm-container-size"
#define y_microwave_model_N_tdm_container_status (const xmlChar *)"tdm-container-status"
#define y_microwave_model_N_tdm_segment_size (const xmlChar *)"tdm-segment-size"
#define y_microwave_model_N_tdm_structure_name (const xmlChar *)"tdm-structure-name"
#define y_microwave_model_N_time1024_states (const xmlChar *)"time1024-states"
#define y_microwave_model_N_time1024_states_l (const xmlChar *)"time1024-states-l"
#define y_microwave_model_N_time128_states (const xmlChar *)"time128-states"
#define y_microwave_model_N_time16_states (const xmlChar *)"time16-states"
#define y_microwave_model_N_time16_states_s (const xmlChar *)"time16-states-s"
#define y_microwave_model_N_time2048_states (const xmlChar *)"time2048-states"
#define y_microwave_model_N_time2048_states_l (const xmlChar *)"time2048-states-l"
#define y_microwave_model_N_time256_states (const xmlChar *)"time256-states"
#define y_microwave_model_N_time2_states (const xmlChar *)"time2-states"
#define y_microwave_model_N_time32_states (const xmlChar *)"time32-states"
#define y_microwave_model_N_time4096_states (const xmlChar *)"time4096-states"
#define y_microwave_model_N_time4096_states_l (const xmlChar *)"time4096-states-l"
#define y_microwave_model_N_time4_states (const xmlChar *)"time4-states"
#define y_microwave_model_N_time4_states_s (const xmlChar *)"time4-states-s"
#define y_microwave_model_N_time512_states (const xmlChar *)"time512-states"
#define y_microwave_model_N_time512_states_l (const xmlChar *)"time512-states-l"
#define y_microwave_model_N_time64_states (const xmlChar *)"time64-states"
#define y_microwave_model_N_time8192_states (const xmlChar *)"time8192-states"
#define y_microwave_model_N_time8192_states_l (const xmlChar *)"time8192-states-l"
#define y_microwave_model_N_time8_states (const xmlChar *)"time8-states"
#define y_microwave_model_N_time_period (const xmlChar *)"time-period"
#define y_microwave_model_N_time_stamp (const xmlChar *)"time-stamp"
#define y_microwave_model_N_timestamp (const xmlChar *)"timestamp"
#define y_microwave_model_N_transmission_mode_id (const xmlChar *)"transmission-mode-id"
#define y_microwave_model_N_transmission_mode_list (const xmlChar *)"transmission-mode-list"
#define y_microwave_model_N_transmitter_is_on (const xmlChar *)"transmitter-is-on"
#define y_microwave_model_N_tx_channel_bandwidth (const xmlChar *)"tx-channel-bandwidth"
#define y_microwave_model_N_tx_ethernet_bytes_max_m (const xmlChar *)"tx-ethernet-bytes-max-m"
#define y_microwave_model_N_tx_ethernet_bytes_max_s (const xmlChar *)"tx-ethernet-bytes-max-s"
#define y_microwave_model_N_tx_ethernet_bytes_sum (const xmlChar *)"tx-ethernet-bytes-sum"
#define y_microwave_model_N_tx_frequency (const xmlChar *)"tx-frequency"
#define y_microwave_model_N_tx_frequency_cur (const xmlChar *)"tx-frequency-cur"
#define y_microwave_model_N_tx_frequency_max (const xmlChar *)"tx-frequency-max"
#define y_microwave_model_N_tx_frequency_min (const xmlChar *)"tx-frequency-min"
#define y_microwave_model_N_tx_level_avg (const xmlChar *)"tx-level-avg"
#define y_microwave_model_N_tx_level_cur (const xmlChar *)"tx-level-cur"
#define y_microwave_model_N_tx_level_max (const xmlChar *)"tx-level-max"
#define y_microwave_model_N_tx_level_min (const xmlChar *)"tx-level-min"
#define y_microwave_model_N_tx_power (const xmlChar *)"tx-power"
#define y_microwave_model_N_tx_power_max (const xmlChar *)"tx-power-max"
#define y_microwave_model_N_tx_power_min (const xmlChar *)"tx-power-min"
#define y_microwave_model_N_type_of_equipment (const xmlChar *)"type-of-equipment"
#define y_microwave_model_N_unavailability (const xmlChar *)"unavailability"
#define y_microwave_model_N_vlan_compression_is_avail (const xmlChar *)"vlan-compression-is-avail"
#define y_microwave_model_N_vlan_compression_is_on (const xmlChar *)"vlan-compression-is-on"
#define y_microwave_model_N_xpd_avg (const xmlChar *)"xpd-avg"
#define y_microwave_model_N_xpd_cur (const xmlChar *)"xpd-cur"
#define y_microwave_model_N_xpd_max (const xmlChar *)"xpd-max"
#define y_microwave_model_N_xpd_min (const xmlChar *)"xpd-min"
#define y_microwave_model_N_xpic_is_avail (const xmlChar *)"xpic-is-avail"
#define y_microwave_model_N_xpic_is_on (const xmlChar *)"xpic-is-on"
#define y_microwave_model_N_xpic_is_up (const xmlChar *)"xpic-is-up"
/********************************************************************
* FUNCTION y_microwave_model_init
* 
* initialize the microwave-model server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t y_microwave_model_init (
    const xmlChar *modname,
    const xmlChar *revision);

/********************************************************************
* FUNCTION y_microwave_model_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t y_microwave_model_init2 (void);

/********************************************************************
* FUNCTION y_microwave_model_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
extern void y_microwave_model_cleanup (void);

#ifdef __cplusplus
} /* end extern 'C' */
#endif

#endif