
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.5-5

    User SIL module
    module onf-ethernet-conditional-packages
    revision 2017-04-02
    namespace urn:onf:params:xml:ns:yang:onf-ethernet-conditional-packages
    organization ONF (Open Networking Foundation) Open Transport Working Group - Wireless Transport Project

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_cb.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "status.h"
#include "u_onf-ethernet-conditional-packages.h"
#include "y_onf-ethernet-conditional-packages.h"

#define XPATH_MAX_LENGTH 2048


/* put your static variables here */


/********************************************************************
* FUNCTION u_onf_ethernet_conditional_packages_ethernet_pac_layer_protocol_edit
* 
* Edit database object callback
* Path: /ethernet-pac/layer-protocol
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_onf_ethernet_conditional_packages_ethernet_pac_layer_protocol_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_ethernet_pac_layer_protocol)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_onf_ethernet_conditional_packages_ethernet_pac_layer_protocol_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_onf_ethernet_conditional_packages_ethernet_pac_layer_protocol_edit */


/********************************************************************
* FUNCTION u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_vlan_id_edit
* 
* Edit database object callback
* Path: /ethernet-pac/ethernet-configuration/vlan-id
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_vlan_id_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_ethernet_pac_layer_protocol)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_vlan_id_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_vlan_id_edit */


/********************************************************************
* FUNCTION u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_edit
* 
* Edit database object callback
* Path: /ethernet-pac/ethernet-configuration
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_ethernet_pac_layer_protocol)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_onf_ethernet_conditional_packages_ethernet_pac_ethernet_configuration_edit */


/********************************************************************
* FUNCTION u_onf_ethernet_conditional_packages_ethernet_pac_edit
* 
* Edit database object callback
* Path: /ethernet-pac
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_onf_ethernet_conditional_packages_ethernet_pac_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_ethernet_pac_layer_protocol)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_onf_ethernet_conditional_packages_ethernet_pac_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_onf_ethernet_conditional_packages_ethernet_pac_edit */

/********************************************************************
* FUNCTION u_onf_ethernet_conditional_packages_init
* 
* initialize the onf-ethernet-conditional-packages server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_onf_ethernet_conditional_packages_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;
    ncx_module_t *onf_ethernet_conditional_packages_mod = NULL;
    onf_ethernet_conditional_packages_mod = ncx_find_module(
        y_onf_ethernet_conditional_packages_M_onf_ethernet_conditional_packages,
        y_onf_ethernet_conditional_packages_R_onf_ethernet_conditional_packages);
    if (onf_ethernet_conditional_packages_mod == NULL) {
        return ERR_NCX_OPERATION_FAILED;
    }
    /* put your module initialization code here */
    
    return res;
} /* u_onf_ethernet_conditional_packages_init */

/********************************************************************
* FUNCTION u_onf_ethernet_conditional_packages_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_onf_ethernet_conditional_packages_init2 (void)
{
    status_t res = NO_ERR;

    /* put your init2 code here */

    return res;
} /* u_onf_ethernet_conditional_packages_init2 */

/********************************************************************
* FUNCTION u_onf_ethernet_conditional_packages_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
void u_onf_ethernet_conditional_packages_cleanup (void)
{
    /* put your cleanup code here */
    
} /* u_onf_ethernet_conditional_packages_cleanup */

/* END u_onf_ethernet_conditional_packages.c */
